In [2]:
import numpy as np

In [4]:
a=np.arange(9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [8]:
b=np.random.randint(0,100,(10,10))
print(b)


[[25 80 30 89 51 75 92 11 79  2]
 [95  3 35 84 57 35 24 48 96 74]
 [31 93 48 19 43 40 53 54 90 57]
 [25 23 68 35 33 62 74 34 91 59]
 [98 71 23 99 33 33 81 56 46 73]
 [52  2 49 84  0 33 63 38 54 80]
 [95 42 86  3 83 48 46 96 44 71]
 [ 5 76 46 19 14 11 19 57 59 28]
 [98 66 64 19 13 47 98  7 35 64]
 [27 95 86  5 61  0 93 23 92 34]]


In [11]:
print(b.max())
print(b.min())

99
0


In [12]:
c=np.arange(2,50,2)
print(c)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


In [13]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [21]:
e=np.random.randint(0,100,(3,4))
print(e)
print(e[1])
print(e[:,2])
print(e[:2,-2:])

[[11 70  4  4]
 [21 33 83 47]
 [42 44  1 31]]
[21 33 83 47]
[ 4 83  1]
[[ 4  4]
 [83 47]]


In [23]:
f=np.arange(12).reshape(3,4)
print(f)
print(f.ravel())
print(f.flatten())

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [25]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(np.vstack([a,b]))
print(np.hstack([a,b]))

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [26]:
h=np.arange(10)
print(np.array_split(h,3))

[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


In [27]:
i=np.random.seed(42)
i=np.random.randint(10,50,4)
print(i)

[48 38 24 17]


In [31]:
j=np.array([10,20,30,40,50])
print(j.mean())
print(j.std())

30.0
14.142135623730951


In [35]:
k=np.arange(16).reshape(4,4)
print(k)
print(np.hsplit(k,2))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]


In [36]:
l=np.arange(1,11)
print(l[l%2==0])

[ 2  4  6  8 10]


In [45]:
m=np.random.randint(0,100,(5,5))
print(m)
m[m>50]=0
print(m)

[[13  8 89 52  1]
 [83 91 59 70 43]
 [ 7 46 34 77 80]
 [35 49  3  1  5]
 [53  3 53 92 62]]
[[13  8  0  0  1]
 [ 0  0  0  0 43]
 [ 7 46 34  0  0]
 [35 49  3  1  5]
 [ 0  3  0  0  0]]


In [50]:
n=np.random.randint(0,100,(5,5))
print(m[[0,2,4],:][:,[1,3]])
print( m[[0,2,4], :][:, [1,3]])

[[ 8  0]
 [46  0]
 [ 3  0]]
[[ 8  0]
 [46  0]
 [ 3  0]]


In [52]:
o=np.array([1,2,3])
o1=np.arange(9).reshape(3,3)
print(o1)
print(o+o1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 1  3  5]
 [ 4  6  8]
 [ 7  9 11]]


In [53]:
a1=np.array([1,2,3])
b1=np.array([4,5,6])
print(np.dot(a1,b1))

32


In [55]:
p=np.array([4,9,16,25])
print(np.sqrt(p))
print(np.exp(p))
print(np.log(p))

[2. 3. 4. 5.]
[5.45981500e+01 8.10308393e+03 8.88611052e+06 7.20048993e+10]
[1.38629436 2.19722458 2.77258872 3.21887582]


In [56]:
q=np.random.rand(4,4)
print(q)

[[0.63340376 0.87146059 0.80367208 0.18657006]
 [0.892559   0.53934224 0.80744016 0.8960913 ]
 [0.31800347 0.11005192 0.22793516 0.42710779]
 [0.81801477 0.86073058 0.00695213 0.5107473 ]]


In [58]:
s=np.array([10,np.nan,20,30,40])
s[np.isnan(s)]=np.nanmean(s)
print(s)

[10. 25. 20. 30. 40.]


In [65]:
t=np.random.randint(0,16,(4,4))
print(t)
print(t[t[:, 1].argsort()])


[[13  4  0  2]
 [ 9 11  7 14]
 [10  5 15 15]
 [ 7  8  3  0]]
[[13  4  0  2]
 [10  5 15 15]
 [ 7  8  3  0]
 [ 9 11  7 14]]


In [69]:
a2=np.array([1,2,3,4,5])
b2=np.array([4,5,6,8,9])
print(np.intersect1d(a2,b2))
print(np.union1d(a2,b2))

[4 5]
[1 2 3 4 5 6 8 9]


In [71]:
x=np.array([1,2,3,4,5])
y=np.array([4,5,6,8,9])
print(np.sqrt(np.sum((x - y)**2)))
print(np.linalg.norm(x - y))

7.681145747868608
7.681145747868608
